apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: bank-app

spec:
  type: LoadBalancer

  selector:
    app: notification-service

  ports:
  - port: 5000
    targetPort: 5000
