apiVersion: v1
kind: Service

metadata:
  name: transaction-service
  namespace: bank-app

spec:
  type: ClusterIP

  selector:
    app: transaction-service

  ports:
  - port: 8080
    targetPort: 8080
